# Generated by Django 5.0.7 on 2024-09-13 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sounds', '0001_initial'),
        ('space_templates', '0001_initial'),
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatesounddetail',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.sound'),
        ),
        migrations.AddField(
            model_name='templatesounddetail',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_templates.template'),
        ),
        migrations.AddField(
            model_name='templatespacedetail',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space'),
        ),
        migrations.AddField(
            model_name='templatespacedetail',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_templates.template'),
        ),
    ]
