# Generated by Django 5.0.7 on 2024-09-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_rename_uri_space_url_remove_space_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacecategory',
            name='thumbnail',
            field=models.CharField(default='gps.png', max_length=255),
            preserve_default=False,
        ),
    ]
