# Generated by Django 5.0.7 on 2024-09-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_key', models.CharField(max_length=12, unique=True)),
                ('time_start', models.DateTimeField()),
                ('password', models.CharField(max_length=255)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=True)),
            ],
        ),
    ]
