# Generated by Django 5.0.7 on 2024-09-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FocusClock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
