# Generated by Django 5.0.7 on 2024-09-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_sound_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='uri',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
